{% set name = "slack-bolt" %}
{% set version = "1.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slack_bolt-{{ version }}.tar.gz
  sha256: 4657e592339797b9b804547a21e6b35dd8e2cd1eab676bfb23960660aae049fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest-runner ==5.2
    - pip
  run:
    - python >=3.6
    - slack-sdk <4,>=3.25.0

test:
  imports:
    - slack_bolt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/slackapi/bolt-python
  summary: The Bolt Framework for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbiette
