{% set name = "slack-bolt" %}
{% set version = "1.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/slack_bolt-{{ version }}.tar.gz
  sha256: af38258d41f801ad9c74503090e0f39accd66c49f667f7e55c97fcdb0e51b886

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner ==5.2
    - pip
  run:
    - python >={{ python_min }}
    - slack-sdk <4,>=3.25.0

test:
  imports:
    - slack_bolt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/slackapi/bolt-python
  summary: The Bolt Framework for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbiette
